### PR TITLE
Notification with update summary on_rightclick

### PR DESCRIPTION
**Pull request by ncoop**
Working for DNF, re. #364.

The other backends should be updated to return, as the second element of a tuple, what they want in the notification body. (I'm not prepared to do them myself.) With no changes, the notif balloon should be OK but will only have the count.

updates-dnf

### CODE REVIEW

**Comment by ncoop** [comment]
Added three commits to PR.

**Comment by facetoe** [comment]
This is cool, I've tested the Cower backend and it works great.

**Comment by enkore** [comment]
Works here nicely with pacman+cower as well, very nice work

**Comment by ncoop** [comment]
Thanks. Note that the `updates` method of any backend must return an int and string.

Also, I haven't tested `aptget` myself.

**Pull request merged**
