### PR TITLE
Calculate battery percentage from energy instead of average of batteries

### PR DESCRIPTION
**Pull request by pajowu**
Average only works if all batteries have the same max energy level. If setups with different sizes the smaller ones influence the percentage overproportianly strong

### CODE REVIEW

**Comment by facetoe** [comment]
Looks like this PR broke the test - https://travis-ci.org/enkore/i3pystatus/builds/222632424.

**Comment by pajowu** [comment]
It seems like some batteries report the charge, while some report the energy. These are different units according to [[1]](https://bbs.archlinux.org/viewtopic.php?id=131025). I am not sure how easy it would be to convert them in case the script meets a device where different batteries use different units. My suggestions is to use this method in case all batteries report either energy or charge (I assume in that cases it can be mixed) and use the old, inaccurate way if they are not the same.

**Comment by pajowu** [comment]
On second looks, it quite easy to convert the units. I fixed that in the second commit. Now it should also work on systems with batteries that report different units

**Comment by facetoe** [comment]
Awesome, looks good.

**Pull request merged**
