### PR TITLE
Add Sonos module

### PR DESCRIPTION
**Pull request by erikmansson**
A module for controlling and displaying information from Sonos speakers. Uses SoCo (can be installed from pip).

### CODE REVIEW

**Comment by erikmansson** [comment]
How can I prevent the import error from becoming an issue?

**Comment by enkore** [comment]
https://i3pystatus.readthedocs.io/en/latest/module.html#handling-dependencies

> To allow automatic generation of the docs without having all requirements of every module installed mocks are used. To make this work simply add all modules of dependencies (so no standard library modules or modules provided by i3pystatus) you import to the MOCK_MODULES list in docs/conf.py. This needs to be the actual name of the imported module, so for example if you have from somepkg.mod import AClass, you need to add somepkg.mod to the list.

In your case this would be `soco`.

**Comment by erikmansson** [comment]
@enkore Any thoughts? Improvements that can be made?

**Comment by enkore** [comment]
Nope ;)

**Comment by erikmansson** [comment]
Thanks :)

**Pull request merged**
