### PR TITLE
setup: add python_requires='>=3.5'

### PR DESCRIPTION
**Pull request by lasers**
I aim to close two issues with this PR. Is `3.6` okay or do you prefer `3.5` instead? See [Debian/stable](https://packages.debian.org/stable/python/python3-all).

1) Bumping to `Python >= 3.6` would allow `f-strings` and other features. Closes https://github.com/enkore/i3pystatus/issues/430.

2) `i3pystatus requires Python '>=3.6' but the running Python is 2.7.16` Closes https://github.com/enkore/i3pystatus/issues/536.

EDIT: FWIW you still have some Debian Stable users based on issue comments.

### CODE REVIEW

**Comment by chestm007** [comment]
I think for compatibility with debian and its derivatives 3.5 is probably better
I have no issues with this, however:

This wont essentially fix #536 as we dont do releases anymore and pypi wont be updated to reflect the new required version :/ I'm unsure why we dont do some sort of automated release through travisCI or circleCI, but it is what it is.

**Comment by lasers** [comment]
>I think for compatibility with debian and its derivatives 3.5 is probably better

Also, #430 might be an old issue according to cc189b4cc21d3938b4c73393ee34244ab360490c and d2436728ed01804ff05e9b80b7056dbd5b4341b1 (Python 3.4).

>This wont essentially fix #536 

True. @enkore After this PR get merged, can you remove or publish last release of i3pystatus for PyPI to essentially fix #536? https://stackoverflow.com/questions/20403387/how-to-remove-a-package-from-pypi

**Comment by thiagokokada** [comment]
@lasers Should we also change `.travis.yml`?

https://github.com/enkore/i3pystatus/blob/master/.travis.yml#L4

**Comment by enkore** [comment]
Thanks. I'm wondering if I should just push a 3.666 release with a setup.py that just says you're supposed to install from git. Would solve both the Python 2 problem (okay, now that Python 2 is EOL except for Red Hat that's kind of a self-solving problem) and the "I installed an ancient version from seventeen years ago by accident" problem.

**Pull request merged**
