### PR TITLE
core: require internet is now updating each 5 seconds

### PR DESCRIPTION
**Pull request by hasB4K**
Hi,

When I updated my PR #521 I noticed that `require(internet)` is not working as expected, and is only runned once for each module (because of the usage of __new__)...
I think that `require(internet)` should update his status globally at a fixed interval (interval that I have set to 5 seconds).
This PR fix that.

Regards,

##
Mathis 'hasB4K' Felardos

### CODE REVIEW

**Comment by hasB4K** [comment]
I think this PR is now fully functional :)

**Comment by richese** [comment]
I think it works just fine as it is. 
I have added some log messages to test it and it gets called every time like it should (tested with external_ip and updates modules).
Are you sure it is not caused by your network like in #234 ? 

```python
import logging

class internet:
    address = ("google-public-dns-a.google.com", 53)

    def __new__(cls):
        try:
            socket.create_connection(cls.address, 1).close()
            logging.getLogger('i3pystatus').info('internet true')
            return True
        except (OSError, socket.gaierror):
            logging.getLogger('i3pystatus').info('internet false')
            return False
```

**Comment by hasB4K** [comment]
You are right @richese. You made me realise that the issue that I have should not even occur...
However this is not caused by my network. Somehow the default `require(internet)` doesn't work properly on my machine, but my PR does. I need to investigate this later. This is weird!

**Comment by enkore** [comment]
"class internet: __new__(): ... return True/False" is pretty much a hacky way of making a function "internet" that also can have that "address" attribute.

It'd be better to just write it as such:

```py
def internet():
        try:
            socket.create_connection(internet.address, 1).close()
            return True
        except (OSError, socket.gaierror):
            return False

internet.address = ("google-public-dns-a.google.com", 53)
```

**Comment by hasB4K** [comment]
Yeah, indeed @enkore, I know that :). I think I'm just too tired today, and I tested it wrong...
Somehow I thought that the predicate was only instantiate once... Added to that an impatient test, you get the wrong conclusion...

I just tested it again, the PR #521 works fine without the #522... (obviously). So I think that the `external_ip` module can be added safely!

Thank you again to you two, @enkore and @richese!

**Pull request closed without merging**
