### PR TITLE
Fix traceback in weather.com weather backend

### PR DESCRIPTION
**Pull request by terminalmage**
It seems that this XML feed may have been changed, as it now returns an
error saying that the location is not valid.

This fixes the traceback when we try to run str functions on None when
the XML keys don't exist in the return data. However, the long term fix
will be to either update the backend to use the updated formatting
(which may be hard as this XML feed appears to be undocumented), or to
simply retire this backend.

### CODE REVIEW

**Comment by terminalmage** [comment]
From watching the requests made when you go to weather.com in the browser, they are using a newer API internally. They seem to be generating an API key on their side to use for API requests. I haven't observed it enough to tell whether or not (or how often) the API key is rotated.

I'll probably need to update the weather.com backend to use this new API, but the question then is what to do about the API key. If every i3pystatus user starts using the same API key, it is probably going to be disabled. So, would it be OK to rely on users to do something like this to get a usable API key?

```
curl -s https://weather.com | grep -i apiKey | grep -v -
          'apiKey': 'c1ea9f47f6a88b9acb43aba7faf389d4',
```

**Comment by enkore** [comment]
This could be done in `init()` or, if necessary, periodically in `run()`, instead of manual key generation.

**Comment by terminalmage** [comment]
Yeah, good call, I like that idea much better than asking someone to get it manually. Doing it in the ``init()`` would insulate the code from the API key changing periodically as well. Great idea!

**Comment by terminalmage** [comment]
I'll try to get a pull request for this in the next couple days.

**Comment by terminalmage** [comment]
@enkore I have rewritten the weather.com backend to use the new API. I'm going to give it at least 24 hours to see if changing conditions result in unanticipated breakage, and I also plan to implement the optimizations needed from https://github.com/enkore/i3pystatus/issues/397 to prevent extra updates when the mouse callbacks are invoked. I will open a separate pull request with those changes and close this one.

**Comment by enkore** [comment]
Thanks! :)

**Pull request closed without merging**
