### PR TITLE
added the alert_command option

### PR DESCRIPTION
**Pull request by plumps**
running a shell command before the battery is completely discharged (~1% left).
You just need to add 

alert_command="<path_to_program> [$@]" 

e.g. alert_command="/usr/bin/systemctl hibernate"

### CODE REVIEW

**Comment by Arvedui** [comment]
I don't think that this should be implemented on this level.

It is the job of you favourite energy management tool to do this and not of a high level tool like a status bar generator.

**Comment by plumps** [comment]
Which is? 

Unfortunately you cannot write udev rules for most systems, as the hardware seldomly generates those uevents. Therefore something has to poll the value of /sys/class/power_supply/* on a regular base, which should be done in a sparse manner.  And as i3pystatus has to do that anyway, I thought it'd be a nice place to trigger other events as well.

**Comment by Arvedui** [comment]
I thought it to be kind of default functionality of tools like tlp.
But obviously I was wrong …

Could you add an config option for the threshold value?
There may be conditions where 1% is not enough and I can imagine that some people are just not comfortable with walking that close to the edge.

**Comment by plumps** [comment]
Sure :)

**Comment by plumps** [comment]
Here's what has changed:
- alert_command became **critical_level_command**
- **critical_level_percentage** to adjust the level, when the command gets triggered. default_value = 1

**Pull request merged**
