### PR TITLE
WIP: Fix pycodestyle errors

### PR DESCRIPTION
**Pull request by EgZvor**
W503 is condracting PEP-8 and was added to the default ignore list by
pycodestyle developers

### CODE REVIEW

**Comment by EgZvor** [comment]
I can revert some changes from the first commit in light of ignoring (by default) W503 and W504

**Comment by EgZvor** [comment]
W503 is not yet in the default ignore list in 2.4.0 version.

**Comment by EgZvor** [comment]
What behaviour are we going to use: ignore both W503 and W504? Or choose one over the other? https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

**Comment by terminalmage** [comment]
@enkore thoughts?

**Comment by enkore** [comment]
https://www.youtube.com/watch?v=ussCHoQttyQ

**Comment by enkore** [comment]
I'm uh just going to merge this real quick

Thanks!

**Pull request merged**
