### PR TITLE
If imaplib2 is installed use the IDLE feature of IMAP to avoid polling

### PR DESCRIPTION
**Pull request by janoliver**
I sort of copied the code together, without really understanding what goes on in the thread checking for mail. It seems to work, though. 

Ideally, there should be some cleanup such as 

    idler.stop()
    idler.join()
    self.conn.close()
    self.conn.logout()

after the script exits, I just don't know where to put those. Also, I moved the login command to the `init` function. I am not sure if this breaks anything when suspending the computer or temporarily losing connection, as I don't know how i3pystatus handles connection losses. 

Feel free to change stuff so it is more stable.

### CODE REVIEW

**Comment by enkore** [comment]
Conflicts with base, please rebase.

**Comment by janoliver** [comment]
I noticed that the module fails when the connection is lost. I'll patch that someday and rebase.

**Comment by janoliver** [comment]
Ok, I added some failure recovery and rebased onto your master.

**Comment by enkore** [comment]
Thanks!

**Pull request merged**
