### PR TITLE
Add module for streaming ABC radio Australia.

### PR DESCRIPTION
**Pull request by facetoe**

### CODE REVIEW

**Comment by facetoe** [comment]
Hmm that's a funny error.. Is Sphinx executing with Python2.7 or something?

**Comment by richese** [comment]
`enum` was added in 3.4 
i3pystatus requieres only 3.2

**Comment by facetoe** [comment]
Ahh OK, I'll just make it a regular class as well.

**Comment by enkore** [comment]
I guess we could bump the required Python version for the next release, since 3.4 and 3.5 are pretty much the standard now

**Pull request closed without merging**
