### PR TITLE
RFC: Improved logging

### PR DESCRIPTION
**Pull request by terminalmage**
This pull request adds a new parameter to the ``i3pystatus.status.Status()`` class
called ``logformat``, which allows the user to set the log format. It also
establishes a default logformat.

@enkore I'd like to get your opinion on this. Maybe the default logformat I
chose should be different? Also, we'd probably want to add this information to
the documentation (I have yet to do this). **EDIT:** I have now added documentation.

### CODE REVIEW

**Comment by terminalmage** [comment]
I added documentation of the proposed new option. I also added documentation for the ``logfile`` param in ``i3pystatus.status.Status()``, and did it in a separate commit to keep the changes atomic. That way, if this pull request gets rejected, I can still take f40eb15 and submit it in a new PR to improve documentation on the already-existing ``logfile`` param.

**Comment by enkore** [comment]
I think the log format is fine, the most important thing (full traceback) will be visible with any format.

**Comment by terminalmage** [comment]
The configuration (logfile, format, etc.) is passed through to child loggers, even ones created within backend instances for the things like updates, mail, and weather.

Just from a development standpoint, I find it immensely useful to have more information in the log entry. For instance, right now I am working on a new multi-backend module which uses the logger very heavily, at different loglevels (with the vast majority of it in debug), and having name of the loglevel at minimum would be very useful.

Perhaps a better default log format would be ``%(asctime)s %(levelname)s:`` ?

**Comment by terminalmage** [comment]
So, right now I am trying to troubleshoot a module that does all of its updates in a separate thread, which is not reliably resuming its checks after my laptop resumes from sleep. I have a lot of log information, but no timestamp for any of it.

**Comment by terminalmage** [comment]
This is the sort of problem I am trying to solve with this PR.

**Comment by terminalmage** [comment]
@enkore Thanks for merging. Please change the default log format if you prefer, I think the one I used in my PR was overly verbose. Something like I suggested earlier (``%(asctime)s %(levelname)s:``) is much more concise and should suffice for the majority of users.

Again, thanks. This will be a TON of help.

**Pull request merged**
