### PR TITLE
Add generic weather module

### PR DESCRIPTION
**Pull request by terminalmage**
This also does the following:

1. Reworks weather.com as a backend for the new generic weather module.
2. Adds ``formatp()`` support.
3. Decouples the support for displaying an icon for the weather conditions from
   the ``colorize`` param. The icons are now available even when colorization
   is not enabled, via the new ``{icon}`` formatter.
4. Adds a ton of formatters to the weather.com module, as well as on_leftclick
   support, to bring it to feature parity with wunderground.

Refs: #331 (closed in favor of this PR)

### CODE REVIEW

**Comment by terminalmage** [comment]
OK, for some reason abf5b6a is still showing up in the PR even though the head of my ``wunderground`` branch points at 66bc56b7. I have no idea why. The former was squashed into another commit during an interactive rebase, and apparently Github is having a hard time figuring that out.

**Comment by terminalmage** [comment]
I should note that this weirdness with Github doesn't affect the functionality of the module, the extra commit was just a one-liner RST fix that I had squashed into another commit to clean up the commit log.

**Comment by enkore** [comment]
Thanks! :)

**Comment by terminalmage** [comment]
No problem, this was fun!

**Pull request merged**
