### PR TITLE
add i3pystatus.utils package to setup.py

### PR DESCRIPTION
**Pull request by enkore**

### CODE REVIEW

**Comment by hcpl** [comment]
Could you also add `i3pystatus.scores` as well?

**Comment by enkore** [comment]
Good catch! Done.

**Comment by hcpl** [comment]
Yeah, now is the right time to switch. And if you switch, consider including `'i3pystatus'` too, because:
```sh
# cd to i3pystatus root dir first
$ python
```
```python
>>> from setuptools import find_packages
>>> find_packages(include=['i3pystatus.*'])
[]
>>> find_packages(include=['i3pystatus', 'i3pystatus.*'])
['i3pystatus', 'i3pystatus.pulseaudio', 'i3pystatus.mail', 'i3pystatus.scores', 'i3pystatus.updates', 'i3pystatus.utils', 'i3pystatus.weather', 'i3pystatus.tools', 'i3pystatus.core']
```

**Comment by enkore** [comment]
Thanks!

**Pull request merged**
